version: '3.5'

services:
  cups:
    container_name: cups
    image: ghcr.io/pocho-labs/cups-avahi-airprint:latest
    # build: .
    restart: unless-stopped
    network_mode: "host"
    environment:
      CUPSADMIN: "cupsadmin"
      CUPSPASSWORD: "cupsadmin"
    volumes:
      - "./config:/config"
